### ISSUE TITLE
Committing changes on the Marshall Page stacks Alert Popup on the top

### ISSUE THREAD

**Issue by Klaus-Michael** [RotorHazard/RotorHazard#119]
Each commit & save to node on the Marshal Page creates a new Alert Popup on top of the page.
Those Alerts Stack and needs to be confirmed manually.
(have a look at my demo video at the end when I wanted to show the Results https://youtu.be/xLMa-gRObHI?t=388)
this can get quiet annoying.
Especially as those Alerts are blocking the Navigation Buttons.

I would prefer of only the last alert is shown, each new alert should overwrite any previous ones instead of stacking

**Comment by HazardCreative** [comment]
The message doesn't only pop up for the user doing the marshaling, but for anyone connected to the system even on other pages. I feel strongly that altering race results is worthy of announcement to all connected clients.

The message serves a dual purpose of confirming that the user's action was successful and informing all other users of the race results change.

Is there an event we could capture that tells the system a user on this page is done working with it? One message is fine for altering multiple races, but there should be a notice of what was changed. We would need to set up a system to capture and deploy those messages that sits separate from the HTML/JS if it will wait to see if multiple races are altered. If we go this route, we also need a new immediate UI signifier that the results were saved so the user of the page has confirmation of their actions.

Perhaps only working with #120 is best here? These messages go into a standardized message handling system which is used by other features as well. I'd prefer those other features to get the benefit of improvements rather than leave as-is and write a new on specifically for this page/function.

Thoughts?

**Comment by Klaus-Michael** [comment]
I notice that the alert is shown for all users and I agree that this is useful.

The main Problem with the Marshal page ist the Stacking of the Alerts, adapting 8 nodes could easily result in 16 Alerts and all those need to be manually confirmed before continuing with the Usage. 

I think it would be OK if any new alert message simply overwrites (or confirms) any previous alert message. So only one confirm is required.
