### ISSUE TITLE
Unable to "Stop a Race" while the countdown is running

### ISSUE THREAD

**Issue by ScorpionTDL** [RotorHazard/RotorHazard#13]
When starting the race its not possible to stop it while to countdown is still running. If you have a long delay this can be quiet annoying if you pressed the start button by accident.

**Comment by HazardCreative** [comment]
Yes, I've noticed this and want to revisit it. It has to do with the timer using sleep() to delay on the server side, which pauses all other execution.

However, the pre-race staging is intended only for the final moments before race start; a very long delay isn't expected here. I would prefer to implement a separate 'time until race' delay. I didn't pull your pre-race announcements in earlier because they conflict with the 'hide staging countdown' setting.

For example, with a separate timer, one could schedule a start for a minute or two in the future, then have a random, hidden 2 to 5 second staging before the race started.

**Comment by ScorpionTDL** [comment]
Yea a separate timer for 'time until race' timer would most likely make things easier and would make pre-race announcements easier and more compatible with random start delays.
I'm currently misusing the start delay by setting it to ~30s to have enough time to put on my googles and participate ;-)

**Comment by BoLtWD** [comment]
"Stop a Race" while the countdown is a good one as you may need to abort a race for safety. Also it would be nice to have an audio announcement something like "RACE ABORTED" other than a beep that a race has been stopped before the race has ended.

**Comment by HazardCreative** [comment]
Fixed with merge of experimental branch @ 220bf6f.
