### ISSUE TITLE
Sort pilots by callsign in the pulldown list when assigning pilots in heats

### ISSUE THREAD

**Issue by RogerBFPV** [RotorHazard/RotorHazard#177]
In the 'heats' setup when assigning a pilot to a slot,  the pulldown list show the pilot callsign then real name.  However the list is sorted by pilot real name..  This makes it almost impossible to quickly find the pilot you are looking for.  

My recommendation is to do one of 2 fixes:
a. Sort the list by callsign, and display the pilots by 'callsign - Pilot name' as is currently done.
or
b. Sort the list by Pilot real name, and display pilots by 'Pilot name - callsign'. 
Either of the above would help a lot.  My preference is a.

**Comment by HazardCreative** [comment]
Some groups refer to pilots by callsign, others by name. I think there needs to be a selectable option on which way they're sorted. In either case, the selected option (name or callsign) needs to be placed first in the lists so that it immediately appears to have this natural ordering from the first character in the list.

Thanks for posting this here. I've been wanting to do this for a while.

**Comment by RogerBFPV** [comment]
I've submitted a pull request that fixes this.  I believe we can close this

**Comment by HazardCreative** [comment]
Thanks for submitting the fix! I prefer to keep the issues open until the fix gets committed into the master branch so there's no chance of it getting lost.
