### ISSUE TITLE
The server's web page must be refreshed if the computer screen turns off for energy savings

### ISSUE THREAD

**Issue by MoonKIE666** [RotorHazard/RotorHazard#201]
I am with version 2.1.0 beta. 

But this problem has been appearing from other previous versions.

What happens is the following: when my computer screen is turned off to save energy, the chrono numbers seem to keep running, but it is not. If I press the STOP RACE button nothing happens, and the other buttons remain gray without doing anything. In order to stop the race and save laps or discard laps, I have to refresh the website with F5. But this wastes some time between batches and leaves you a little worried if you are a newbie, because you don't know if it is working well.

**Comment by HazardCreative** [comment]
It's likely that the socket connection has dropped. Perhaps we can test for and re-initiate the connection when this happens. The [Page Visibility API](https://www.w3.org/TR/page-visibility/) is well supported now. Perhaps we can couple this to socket = io.connect? Or should we do more robust checks for an open connection as we go along anyway?

In this instance, the timer IS still running, actually—but since there's no active connection to the server, you can't send commands. (The save/discard buttons become active only after a race has stopped.)

**Comment by HazardCreative** [comment]
This may have been resolved by #440 and #446. Testing is needed.
