### ISSUE TITLE
Small graphics in the MARSHAL tab

### ISSUE THREAD

**Issue by MoonKIE666** [RotorHazard/RotorHazard#202]
I am with beta version 2.1.0

This weekend we were testing the last beta and I had to look more than once in the MARSHAL tab, because many people came and the vtx gave me very different readings. Well, when I entered MARSHAL to calibrate well there were times when very small graphics appeared to me, and they did not change size until I entered some value in EnterAt or ExitAt.

**Comment by HazardCreative** [comment]
This happens because the graph library's auto-scaling feature doesn't work well with statically rendered graphs (it's really designed for moving graphs). Adjusting some of the points that the graph draws with can trigger a redraw with new scaling. Maybe there's a way we can programmatically trigger the redraw as well.
