### ISSUE TITLE
LEDpanel-16x16-pause.PNG not using the full 16 x 16 leds

### ISSUE THREAD

**Issue by BoLtWD** [RotorHazard/RotorHazard#237]
The pause 16 x 16 png is not using the full panel of leds compared to other images.  There is a row of leds 2 lines not used around the edge of the pause making it not clear on a camera. 

I have stretched the pause to the sides and in height using the leds on the sides and giving the mid section 4 leds not lit up. 

![LEDpanel-16x16-pause](https://user-images.githubusercontent.com/25492262/73971416-c0254e80-4916-11ea-9b01-b9a1f197aea5.png)

**Comment by HazardCreative** [comment]
This is intentional. The size of the image is another signifier (in addition to shape and color) that a race is about to begin. Cameras that cannot make out the shape or color due to panel position, lighting condition, lens and sensor deficiencies, etc. are still able to use the start signal because the change in shape between staging and start makes it obvious.

**Comment by BoLtWD** [comment]
I must admit after scuffing up one side of plastic with some P1000 grit paper and securing this side to the leds panel this reduced direct light from the leds affecting the camera on a whoop and the original as you stated looks a lot better now.

**Comment by HazardCreative** [comment]
Make sure you reduce the brightness with the available slider. The best for FPV cameras is where the LEDs appear to be the same brightness as a physical object. Indoors especially, this will be a really low value.
