### ISSUE TITLE
Data export formats

### ISSUE THREAD

**Issue by HazardCreative** [RotorHazard/RotorHazard#253]
What formats are desired for race data exports? Which reports should be exported, and what data within them?

**Comment by qtifs6905** [comment]
For me I like to have:

Round, Pilot, lap 1 time, lap 2 time, lap 3 time, lap 4 time, lap 5 time, lap 6 time, PB / Fastest lap

or

Round
Pilot, lap 1 time PB / Fastest
         lap 2 time
         lap 3 time
         lap 4 time
         lap 5 time
         lap 6 time

repeat for each pilot

**Comment by MoonKIE666** [comment]
For me the interesting thing is that you could see the same information generated by the results page itself in some excel format of google. In order to upload those results to a GOOGLE DRIVE without editing permissions so that everyone could see it

**Comment by RogerBFPV** [comment]
A recent request from a race director was to export the results in CSV form based on the win condition: (  pilot, time, position)
2dogrc,74.8,1,
rogerb,77.2,2

**Comment by ErikBorra** [comment]
JSON or CSV with the following information:
* For laps: pilot {id,name,handle}, (any other registration information), lap {number, time, valid, position}, heat {id, name, number, length}, round {type, number}, race {id, name, date}, class {id, name}, event {id, name, date}. Note that when lap number == 0, the time would be the time since start.
* For events: pilot name, overall position, event {id, name, date}, series {id, name, date}

With such information rankings like https://rankings.platformdroneracing.nl/?series_id=9 could be generated.

**Comment by KennyVDSypt** [comment]
I think CSV has a lot to offer. I love to put our data in excel. You can customize the way it looks as you want and easely convert them to jpeg for posting on social media etc.

For the data, Is it possible to have a list of checkboxes to choose what results you want the timer to spit out before you click the export button?
We did a double elimination race last weekend. After a lot of copy pasting (6pools) from the server this is our result.

![Laptimes Summary](https://user-images.githubusercontent.com/39454384/89461497-5aead280-d76c-11ea-87a3-a7abbcb44878.jpg)
![Qualification Pool 1](https://user-images.githubusercontent.com/39454384/89461502-5c1bff80-d76c-11ea-8a77-c0803d99603a.jpg)

**Comment by pulquero** [comment]
This is probably a good candidate for pluggable modules.

**Comment by HazardCreative** [comment]
Looking for comment on https://github.com/RotorHazard/RotorHazard/tree/data-export .

Not the JSON/friendly/results is not yet implemented; I'm unsure if it's needed and would like to hear from users as to what it might look like if it is.
