### ISSUE TITLE
RXes VCC connected to AREF pins - idea

### ISSUE THREAD

**Issue by szafranski** [RotorHazard/RotorHazard#276]
Idea: connecting RXes VCC line (usually about 3V3) to the AREF pins of Arduinos + enabling AREF as external based.

Advantages - readings "scaled" better and higher resolution of readings - if I get it right?
Also readings will be independent of Arduinos supply voltage.

Disadvantages - 4 more PCB traces

What do you think?

**Comment by HazardCreative** [comment]
There's really no advantage to doing so.

Each node already has very different sensitivity characteristics, and the system is designed around that. Making the nodes of one receiver appear more like the nodes of another is irrelevant as all are treated independently. 

RSSI carries a lot of noise. Small changes are always insignificant, so we don't need additional resolution within them. In fact, the node code actively reduces resolution before sending to the server in order to conserve bandwidth.

If you want to connect the references on your own equipment, doing so will not affect the timer's performance unless your receiver then sends unusually high values (above 512). In this edge case—which I have never encountered or heard of—the current strategy of a 5V reference and 3V signal actually could improve performance by preventing swamping.
