### ISSUE TITLE
LiveTime Integration

### ISSUE THREAD

**Issue by fpvMarkS** [RotorHazard/RotorHazard#307]
It would be nice to have a way to adjust the node settings from within LiveTime ... I think I understand the rotorhazard goes into slave mode after LiveTime connects on port :5000
Any thoughts on this ???

**Comment by szafranski** [comment]
As far as I know you can (and even have to) still to open and setup RotorHazard server using a browser. All setups like low and high threshold etc are than being "used" by LiveTime I suppose.

**Comment by HazardCreative** [comment]
Currently you log into RH as you would if it was running stand-alone. A dedicated page for LiveTime is coming.

**Comment by ErikBorra** [comment]
Did the following to use this branch
```
pi@RotorHazard:~ $ sudo systemctl stop rotorhazard
pi@RotorHazard:~ $ git clone git@github.com:RotorHazard/RotorHazard.git
pi@RotorHazard:~ $ cd RotorHazard
pi@RotorHazard:~ $ git checkout livetime-settings
pi@RotorHazard:~ $ git merge master
pi@RotorHazard:~ $ cd ..
pi@RotorHazard:~ $ cp RotorHazard2.2.0-working/src/server/config.json RotorHazard/src/server/
pi@RotorHazard:~ $ cp RotorHazard2.2.0-working/src/server/database.db RotorHazard/src/server/
pi@RotorHazard:~ $ sudo systemctl start rotorhazard
```

In Livetime, go to decoder > connections, chosse Delta 5 and enter the IP address of the Rotor Hazard timer. Livetime can properly connect to the decoder.
The decoder settings page of LiveTime picks up the frequencies set with RH (either through /settings or /decoder). However, the LiveTime decoder settings page still shows the (global) node tuning parameters of Delta 5: calibration threshold, calibration offset, trigger threshold. For each node, a separate trigger is displayed but not changeable. This 'trigger' corresponds with 'EnterAt'. No values for 'ExitAt' are displayed. 

When clicking 'Sync Event Frequencies' within LiveTime, the /decoder page does not live update. Hard reload is needed to update the frequency setup.

In order to do all the sensor tuning within LiveTime, we should probably talk with Cory Kroll from LiveTime FPV. It'd be great if frequencies could be set for each node, delta 5 tuning parameters were removed, and EnterAt and ExitAt values could be inserted via the LiveTime decoder settings page. 

Will test passing quads tonight.

**Comment by HazardCreative** [comment]
Thank you for the test. Not many who are truly familiar with LiveTime have done this yet and reported back.

I'll take a look at the 'sync event frequencies' item; that sounds like a RH-based issue.

LiveTime does not yet recognize RotorHazard as a separate project, but we do have an open discussion with Cory about this. I think the plan is to launch RH's '/decoder' page into a dedicated dialog/window.

**Comment by HazardCreative** [comment]
I got that frequency updating issue resolved, though the build tests don't understand the new method yet.

**Comment by ErikBorra** [comment]
Will test it tomorrow.
