### ISSUE TITLE
Node configuration warnings only valid after collecting pass data

### ISSUE THREAD

**Issue by HazardCreative** [RotorHazard/RotorHazard#33]
The node configuration warnings act on data collected by the node during operation. They are only valid once a lap of the course has been completed on the current frequency. (Changing frequencies resets the NodePeak, which invalidates the data.)

Until that has happened, the data isn't useful and could cause users to configure improperly. Should we have a notice about this? Or is there a way to detect when the data is good enough to use?

**Comment by ethomas997** [comment]
I don't think that always showing a warning when ExitAt < nodePeakRSSI is workable because 'nodePeakRSSI' is always reset at server startup, and I can't see a way to determine whether or not a good 'nodePeakRSSI' value has been detected.  Perhaps warn or reject if a new ExitAt value is less than 'nodePeakRSSI'?
