### ISSUE TITLE
Channel select should be on name instead of frequency

### ISSUE THREAD

**Issue by ErikBorra** [RotorHazard/RotorHazard#355]
Currently, when selecting overlapping frequencies, it defaults to the first one in the list. E.g. when selecting D2 it will show R2, as both are on 5695; when selecting D5 it will show A4, as both are on 5805. This is confusing for participants, as R2 and A4 will show not only in the frequency setup but also e.g. heats in the event tab, while the should be flying D2 and D5 respectively.

**Comment by HazardCreative** [comment]
The issue here is that RH doesn't store band and channel anywhere. The database stores frequency, and the web front-end translates that to a band/channel designation. When it comes time to populate the identifier, "5805" is the only information available. RH supports any frequency in the range and not just those that are named by a band/channel combination, and this was a big advantage when the DJI FPV system was released.

If the band was stored as well, the data would have to be checked for conflicts when loaded and ignored if there was a mismatch.

**Comment by ErikBorra** [comment]
I understand. Just pointing out that it is confusing for pilots not behind the system. Especially DJI pilots, they do not care about frequency, just the channel number. A4 is thus weird, when they expect D5.

**Comment by HazardCreative** [comment]
Yep! Totally understand. My reply wasn't intended as criticism of the idea. There's a real benefit if pilots are using the system.

**Comment by ryaniftron** [comment]
Can we assess the level of effort for this? 

From a VRx perspective, I can make the module work with either band/channel or frequency. If you set the frequency using band/channel to one of the nondetermistic ones, then it can remember the band/channel instead of the frequency. Happy to do this.

**Comment by HazardCreative** [comment]
Closed with #492
