### ISSUE TITLE
/race: change save/discard laps from buttons to a checkbox

### ISSUE THREAD

**Issue by ErikBorra** [RotorHazard/RotorHazard#363]
When stopping a race you either want to save or to discard the laps associated with that race. RH currently provides two buttons; one of them needs to be clicked after each race. 

There is however a default action when running an event: save laps. This allows for result generation and marshalling. 

I suggest to thus make 'save laps' the default action. This can be achieved by using e.g. a check box with the label 'save laps'. When checked the laps are saved, when unchecked the laps are discarded. The last used setting should be used in the next race.

**Comment by HazardCreative** [comment]
At what point do you propose the results would be committed or discarded? Race stop? Next race start? Something else? And why?

**Comment by ErikBorra** [comment]
Results should be committed when clicking stop race. Cleaning up results can be done via the marshall page. On /race you want to be able to advance to the next heat as quickly as possible. E.g. when running an event where everybody gets to fly 3m and the next heat is up in 2m, as we usually do when flying with more than 8.

**Comment by ethomas997** [comment]
Seems like if there's a "save" checkbox that could be defaulted to off, resulting in the race data being discarded when the 'Stop' button is hit, it could lead to accidental discarding of the race data, which would be bad.

How about if we enable the 'Save' button while the race is running (and maybe rename it 'Stop & Save Laps').  Then the action could be completed in one click.  Still have the 'Stop Race' and 'Discard Laps' buttons.

**Comment by ErikBorra** [comment]
@ethomas997 good observation. The 'stop & save laps button' is a great suggestion!

**Comment by HazardCreative** [comment]
A few things to consider:
* Combining these actions requires that the operator either reviews data while it is still being collected (and quads often continue to trigger false crossings as pilots walk past the gate) or the operator knowingly commits data into the results without fully reviewing it.
* Save/discard also clears the lap list on the run page. It doesn't do this on the spectate page, but for smaller groups, (arguably RotorHazard's primary target audience), only one system is usually running. With small groups, the members largely congregate around and consult the run page together before it's cleared. With this change, the race would continue running and collecting data while the group members reviewed results.
* Some users (@ethomas997 included) have expressed interest in a 'ready' state in between stop race and start race. This is mostly a signal to pilots that it's safe to enter the course, place quads on the blocks, do VTx spot-check tests, etc. It differs from the 'stopped race' state where quads may still be in the air (likely having just been called to land) and these actions are still unsafe. Leaving these separate provides a natural state change: I display the red X on my LED panel at stop race and shut it off at save/discard. If removed, organizers would need to do this manually.
* In considering how 'current race' marshaling can be accomplished, the state between 'stop' and 'save' may be the most appropriate time.

I am thinking that keeping the 'stop' button in place but enabling 'stop and save' (and also 'stop and discard') could handle all of these cases, but I'm interested in any additional feedback that people might have.

**Comment by ErikBorra** [comment]
Hi @HazardCreative,

I admire your involvement and quick response!

a) correct. Laps can always be cleared in Marshall page. 
b) didn't consider that, although 'stop and save' and 'stop and discard' would allow for this
c) didn't consider that either. Not sure whether track signaling should always be tied to these particular buttons though
d) agreed. 

Maybe I just need to learn how to use this system :p

**Comment by ethomas997** [comment]
I'd worry that a 'stop and discard' button would make it too easy to accidentally toss results that wanted to be saved.  Would it make sense to have the 'Save Laps' button enabled and named 'Stop & Save Laps' while the race is running, and have the name change to 'Save Laps' when the race is stopped?  (And otherwise have the buttons run the same as now.)

**Comment by HazardCreative** [comment]
I was thinking about this again in order to implement and there's an additional consideration. Lap crossings always happen in the past—there's lag time between when the pass occurs, when the crossing event completes so the node can determine what time it happened and store it, when the server collects the crossing from the node, and when the time is finally recorded into the data. This all happens pretty quickly, but it can still take a couple seconds (particularly the first step). When the race is in the 'stopped' state, lap crossings are still checked to see if they happened before the race was stopped. These are always prevented once the save/discard phase begins. So this behavior will either prevent very recent laps from being recorded even if valid, or a check and delay will need added so that all nodes can be assured to not contain a crossing.
