### ISSUE TITLE
Live graphical tuning

### ISSUE THREAD

**Issue by ErikBorra** [RotorHazard/RotorHazard#365]
Setting EnterAt and ExitAt via the RSSI graph should be possible whilst a race is running. This would be hugely beneficial to get a good tune, both when the very first heat is still running and later on, when nodes start to drift or when a different pilot uses the same frequency.

In order for this to work, marshalling should work on live data rather than on saved laps. The RSSI graph should thus be cumulative instead of having a fixed time window (as is now the case in /race and /settings). 

This also means that the graphs should be wider. My suggestion is to have one 'line' per node, not unlike the marshall page.

**Comment by HazardCreative** [comment]
Graphical tuning is still pretty new and was basically a last-minute addition to 2.1; there's definitely a desire to expand this in the future to be useful with realtime data.

The specifics of what's proposed here are interesting but several difficult issues need resolved.

- The live RSSI graph and the history used for marshaling are actually two different data sets. The history algorithm throws away many data points flagged as 'non-essential' in order to maintain high accuracy with low bandwidth. Race history data may be delayed before being collected by the server. A live graph would frequently appear broken as the incoming data was delayed or (intentionally) missing.
- Live redrawing of cumulative graphs may have a significantly higher CPU load for the browser. This will not ease up as many data points will be calculated over and over again without being cleared away.
- Currently, processing of history data (marshaling recalculation) is done in the browser and the results sent back to the server when committed. This allows for very fast update rates for the visual tool. To recalculate laps on real-time data, the browser would always need a full and current copy of the data set—new history data must be streamed in live without interruption. Error checking to ensure all data is being used to recalculate with would be required.

**Comment by ErikBorra** [comment]
Thanks for your prompt reply. I'd be happy to look into this (at some point in time).

I'd like to understand the specifics of the difference between live and historical RSSI data in RH. Could you point out in the code where to find the history algorithm?

**Comment by HazardCreative** [comment]
History collection happens in /src/node/rssi.cpp . Live RSSI dumps out the latest value to come out of the filter on each data collection step in /src/node/commands.cpp . Neither provide a truly complete picture of the RSSI sampling because doing so is impossible with the bandwidth and storage space available.
