### ISSUE TITLE
Result page discards minimum lap time

### ISSUE THREAD

**Issue by ErikBorra** [RotorHazard/RotorHazard#370]
It seems that the results page does not take into account the minimum lap time.

The last three sessions I have run time-up training sessions. We just put the timer down, start the 'race' and have people fly lipos whenever they want. Sporadically I stop a heat and do some marshalling (and set to node) if laps weren't picked up correctly. 

In the race interface, laps are picked up correctly and invalid laps (< minimum lap time) are highlighted. Stopping the race and saving the laps (with discarded laps still highlighted) seems to lead the results page to include those highlighted invalid laps as valid laps. 

Is this on purpose, or is that something we can get fixed :)

**Comment by HazardCreative** [comment]
Working as expected.

The default, strongly recommended behavior for minimum lap handling is simply to highlight them. This makes you aware that there is an issue. Simply discarding the later pass is often the wrong decision. A short lap often appears because a pilot crashed near the gate or missed it and circled back around. In both these situations, it's the last pass that is valid and not the first one.

With the highlight, you can use the 'X' during the race to choose the right laps to remove, or use it as a flag to ask questions of the spotter and take a trip through marshaling immediately after the race concludes.

If you are confident that these laps should always be forever removed, change the minimum lap handling to 'discard new short laps'. They will be ignored as they occur. It is not a recommended setting because it very often leads to recording the wrong the wrong choice without notifying the operator at all.

**Comment by ErikBorra** [comment]
OK, so before stopping/saving a race I should thus make sure to review and delete the highlighted laps?

Best,

Erik

**Comment by HazardCreative** [comment]
You should stop as soon as all pilots are done racing, so that new passes like walking past the gate aren't recorded. (At that point you are also just increasing your file size for no benefit.) You can adjust before or after saving, as desired.

**Comment by ErikBorra** [comment]
This works fine in races with a predetermined time limit. Not in practice sessions. See also issue #368
