### ISSUE TITLE
Switching channels

### ISSUE THREAD

**Issue by ErikBorra** [RotorHazard/RotorHazard#372]
During an event I might want to add pilots to a heat, change some channels if pilots have bad reception, etcetera. Currently I will have to make a new heat, e.g. just to switch the frequency of two pilots. Is there an easier way around this? 

I get that heats should be tied to a round. But why can we not change the 'members' of a heat once race laps have been recorded?

**Comment by HazardCreative** [comment]
Yes, make a new heat. RH needs the history to know which pilot recorded the laps. This is used for adaptive calibration, among other things. The seat number is important as well since each node has its own unique sensitivity characteristics.

Resolving Issues #337 and #351 should help improve the UI for this case.

In the future, changing pilots of heats will be made possible. However, the change will be retroactive and intended to correct mistakes in heats that were determined only after the race was running.

**Comment by ErikBorra** [comment]
#337 in particular would be reasonable and workable. Thanks.On Jul 20, 2020 14:54, Hazard Creative <notifications@github.com> wrote:
Yes, make a new heat. RH needs the history to know which pilot recorded the laps. This is used for adaptive calibration, among other things. The seat number is important as well since each node has its own unique sensitivity characteristics.
Resolving Issues #337 and #351 should help improve the UI for this case.
In the future, changing pilots of heats will be made possible. However, the change will be retroactive and intended to correct mistakes in heats that were determined only after the race was running.

**Comment by ErikBorra** [comment]
After discussion with
