### ISSUE TITLE
Define/display version code

### ISSUE THREAD

**Issue by ethomas997** [RotorHazard/RotorHazard#41]
Define program version code in 'server.py' (same as version in [RotorHazard-Releases](https://github.com/RotorHazard/RotorHazard/releases)) and display it in the GUI, either in the title or via a menu item.  Could/should also have a Help-About-style window that shows this and other version codes (like SERVER_API, NODE_API_LEVEL for each node).

**Comment by HazardCreative** [comment]
* Version code should note release version or a more recent pull.
* Server API value makes sense.
* Node API values should show all of them, if there are differences among nodes—otherwise one value is fine if they are the same.
* Recommended node API value should also be shown, possibly with a highlighted warning if they do not match.
