### ISSUE TITLE
issue with switching node to saturated channel

### ISSUE THREAD

**Issue by frizzle101101** [RotorHazard/RotorHazard#460]
sometimes when the rssi is saturated on a channel (the vtx beside the timer) the only way for it to read the propper rssi is if you move away from the node(or turn the vtx off then on) and then test closer again, to best recreate this sit beside your timer then switch the vtx channel to another channel then change the node to that channel it will appear to be reporting non-saturated or no signal rssi like on the previous channel until the vtx moves away and come back(or turn the vtx off then on

**Comment by HazardCreative** [comment]
Thanks for the report.

I was not able to reproduce this, but even if I could it sounds like a hardware issue with the modules that we could not adjust. The only condition I can think of where this could cause an issue is if you are starting the race from within the start gate. That's not recommended because your start times would be logged erratically. It's always better to start outside the gate. If you want a similar distance, launch off to the side and change the 'first crossing' behavior to start counting at lap 1. (This feature is available in the latest beta.)

**Comment by HazardCreative** [comment]
Closing old issue with provided workaround. Reopen if new information/reproducible case is available.
