### ISSUE TITLE
Software instructions and requirements.txt mismatch

### ISSUE THREAD

**Issue by szafranski** [RotorHazard/RotorHazard#493]
Hello, I just read the Software Setup page cause I wanted to be sure that OTA scripts are up-to-date. I found werid mismatch. So now there are no steps to install LEDs support besides information that the rpi281x library will be installed with other packages listed in "requirements.txt". Unfortunately the requirements.txt contains that library only in "master" branch/release. In "2.3.1" ("stable") branch there is no LED library listed in requirements, despite Software Setup instructions mentioning it. 

![image](https://user-images.githubusercontent.com/23621888/106381421-d4c8e500-63b8-11eb-9cd1-5c4e0d27d503.png)

![image](https://user-images.githubusercontent.com/23621888/106381453-1bb6da80-63b9-11eb-9c5e-af6c4f6d90f9.png)

![image](https://user-images.githubusercontent.com/23621888/106381460-27a29c80-63b9-11eb-995e-50e28da69cbe.png)

Cheers!

**Comment by ethomas997** [comment]
Good catch noticing that.  It's a little tricky because the 'rpi-ws281x' library is Raspberry-Pi specific (this is handled in the current 'master' code via the new 'reqsNonPi.txt' file).  I think the best fix for this is to modify the instructions on v2.3 to specify installing the library directly.  This change can go into a v2.3.2 update-release.

**Comment by ethomas997** [comment]
Resolved via 7c2eb6a371d0833215c29c302d985bf6b5cb0c3c
