### ISSUE TITLE
RSSI Readings

### ISSUE THREAD

**Issue by martinglass** [RotorHazard/RotorHazard#547]
Any ideas what's happening here (see screenshot)? It's fresh install - empty database. Version 2.3.3, but same thing happened with 2.3.0

Entering a new number in the box doesn't change the line height (Y-axis) in the chart. But cusing the up/down arrows changes both the chart line and the box number.

For example, the red-line (EnterAt) number on the Graph started at 125, while the number in the EnterAt box (to the left of Capture) started at 115. I reduced the Enter At level using the down arrow, clicking it 10 times. Each of the numbers decremented by 1.

Same thing for all nodes. Similar problem for ExitAt (but it's difficult to tell as the Orange-line (ExitAt) number isn't shown).

Shouldn't these numbers be the same? And wouldn't it be a good idea to show the ExitAt number on the chart too?

![RotorHazard RSSI](https://user-images.githubusercontent.com/41255030/113513897-a952aa00-9563-11eb-8f8d-01ec04d7747b.png)

**Comment by HazardCreative** [comment]
Working as intended.

The on-graph numbers on the the graph are not the enter/exit values, but the graph extremum (min/max of visible area). The visible graph area is a a function of the enter and exit values, but also the highest and lowest values the timer has seen (since the last frequency change). The timer is doing its best to keep the most usable range possible in view.

The range adjusts on the browser "change" event. That happens immediately when you click the arrows, but you have to "finish" typing to trigger it—usually by deselecting the box in one way or another.

I see you must have started your timer (or just changed frequencies on all nodes) recently because the peak and nadir values are basically just +/- 1 from the current value. When that's true, the graph has no real data to work with yet so it's just making a best guess at what the most useful values will be. As you power on transmitters and run them through the timer, the graph range will settle and improve based on observed lows and highs. Until some of those have gone by, the graphs aren't useful for tuning anyway.

Even if we wanted to, it would take extreme effort to set the on-graph numbers to match enter and exit. They are provided by the graphing library. If you want to know the enter and exit, you can easily see their values just below.

**Comment by martinglass** [comment]
It's a tribute to RotorHazard that I've never had to play around on this page before, even though I've been using RotorHazard for our personal practice sessions for a long while. However, I've recently got a DJI Digital video system and RotorHazard failed to adapt to the digital signals, hence my attention to the Sensor Tuning page.
My bad - the chart numbers shows the extremus of the y-axis, but I read it differently (I read the max value number as the EntryAt value, not the Y-Axis maximum, and I didn't notice the Y-axis minimum number at all, lol).
Can I draft some changes to the Documentation, which may help explain it better to newbies?

**Comment by HazardCreative** [comment]
Yes, please feel free to contribute documentation updates for review.
