### ISSUE TITLE
feature request: Hide disabled noded on Race and Current Page

### ISSUE THREAD

**Issue by Klaus-Michael** [RotorHazard/RotorHazard#55]
add a option to hide the nodes that are set to disable on the Race and Current Page. Only show those nodes that are active.
Additional hide all nodes where no Pilot is assigned.

**Comment by HazardCreative** [comment]
I'm leaning towards this as normal behavior. Is there a good reason to make
it optional?

**Comment by Klaus-Michael** [comment]
I agree for the disabled nodes. As this is typically the same for the complete event.

For the nodes where no pilot is assigned for this specific heat it might be usefull to have the option to NOT hide them. Simply because the next heat might have a pilot on this node and one wants to keep the layout the same and each node at the same position on the screen. I can imagine that this comes down to personal preference. 

For me personally: hide everything that is currently not in use would be enough ;-)

**Comment by HazardCreative** [comment]
I looked into this. The CSS adjusts the width of items in layout based on how many elements exist in the HTML. This means using display:none leaves holes in the UI. The node HTML is generated at page load time. If I only load HTML for enabled nodes when the page renders, heat changes and frequency changes can't alter the node list properly—they don't generate node HTML.

I think to do this right, the node list would have to be ripped out and replaced with a version rendered by Javascript instead of Python. This is probably the only possible way to remove nodes which are disabled by pilot=None.

Does it make sense as an intermediate measure to have nodes disabled by frequency=None not appear? A page load is required if the disabled nodes change. Getting the list of nodes out of sync this way would be infrequent because it can only happen if a second tab/user makes the change while another one has the Race/Current tab open.

**Comment by HazardCreative** [comment]
Hiding nodes disabled by frequency implemented by 06851a2.
