### ISSUE TITLE
Feature Request: Export Data in JSON format for third party hardware

### ISSUE THREAD

**Issue by Ryanf55** [RotorHazard/RotorHazard#56]
Hello, I am creating a desktop GUI in python to interface with FPV hardware. I would like to retrieve data from the RotorHazard timing system through a HTTP/JSON API. I have put together a few essential request types to start out with.

**get_heat_info(n,p):** Returns the results of heat "n" for pilot "p" containing fields:
 `"pilot_handle"
"laps"
"time_total"
"time_avg"
"time_fastest"`
Error conditions:
If n is greater than the number of completed heats, return "n": actual_number_of_completed_heats
If p is greater than the number of non-empty pilots in  a heat, return "p":actual_number_of_pilots_in_heat

**get_pilot_info(n or pilot_handle):** Returns the frequency in use by racer "n" or racer with name of pilot_handle containing fields:
`"band_channel_ID"
"frequency_numeric" `
Error conditions:
If n is greater than the number of pilots at the heat, return "n":actual_number_of_pilots_in_heat
If "pilot_handle" does not exist, return `"pilot_handle":"invalid"`

**get_race_status():** Returns a status message for the race such as:
`"status":"idle"`
or
`"status":"arming"`
or
`"status":"racing"`

I'm relatively new to Python and JSON formats, so please feel free to adjust these recommendations on what would work better and how the data is stored in RotorHazarard software. I'm also not set on any of the naming conventions above - use whatever is most convenient. 

Thank you in advance.

**Comment by HazardCreative** [comment]
I think this is a great idea for interoperability with other equipment and systems. There are many possibilities here with how such an API could get used, both in hardware and in software.

I got as far as proof of concept on this and it'll certainly be possible to respond to HTTP requests with JSON. I'm glad you're flexible on the spec because the internal data doesn't quite line up with your API calls, but I'm sure we can work together to expose the info you want.

At least to begin with, you can expect a set of endpoints that are a straight dump of the existing data structures: https://github.com/RotorHazard/RotorHazard/blob/master/src/server/server.py#L282

I'm trying to think through the best way to signal a time-sensitive event such as a race start.

**Comment by Ryanf55** [comment]
Great! Thanks for the link to the existing data structures. It makes sense to keep pilot data separate from the actual heats/frequencies. Should I modify my original post to match the existing spec, or comment a revision below?

 Once we get data import/export working between applications, I'll create a separate feature request for the time-sensitive info.

Does the existing software support storing and sharing database files, or is it only stored internally? If it does support sharing, can you attach an example file here?

**Comment by HazardCreative** [comment]
This issue won't be the API documentation, so I don't think it's necessary to restate the spec.

The database file is an SQLite database generated by Python. You can save and restore them if you have access to the pi's filesystem. The DB file probably shouldn't be considered stable enough to work with directly, since the database structure changes from time to time as features are added. Some sort of import API would do a better job parsing files into the correct locations vs. working with the db file.

**Comment by Ryanf55** [comment]
Ok. Well I am writing the software for my ground equipment in python; I might as well have it also run on a Rasberry Pi 3 B+. Let me know if there is any way I can test, or if you have any questions on my implementation. 

Until then I will familiarize myself with JSON and SQLite.

**Comment by HazardCreative** [comment]
Here's a rough and early implementation. https://github.com/RotorHazard/RotorHazard/tree/JSON-API

API Endpoints:
/api/pilot/<int:pilot_id>
/api/heat/<int:heat_id>
/api/class/<int:class_id>
/api/format/<int:format_id>
/api/profile/<int:profile_id>
/api/race/current
/api/race/<int:heat_id>/<int:round_id>
/api/status
/api/options

The endpoints for single pilot, heat, class, format, profile, status, and options are likely to be pretty stable as-is. Races are a little more volatile since it would likely be far more useful to have calculated stats rather than only getting a dump of raw lap data. I also understand that there's no current method to get the entire set of pilots/heats/classes/formats/profiles/races, and those would be desirable as well. But this is a start.

**Comment by HazardCreative** [comment]
Added /all endpoints for most data types (such as /pilot/all) and improved existing endpoint data and structuring.

What else should we include in the v1 JSON API?

**Comment by Ryanf55** [comment]
Hmm. Still trying to catch up on everything. 

To start off:
1)I did see in src/server/server.py the @APP.route api_status returns "num_nodes" and "race_status". If 8 nodes are setup and only 5 pilots are racing, where would that data appear?
2)I don't see protections if a request is out of index bounds. A generic return of the number of valid entries like I mentioned might work. 
3) Can it supply the Race_laps_winner_name of the last valid heat if called when the race status is not in a race?

Thank you for the API support.

**Comment by HazardCreative** [comment]
1: The timer determines active channels by looking at both the frequencies and heats. If either a node is disabled (frequency set to 0) or a heat slot is set to none (0) then no time is recorded. Note that the current profile's frequency set will always have 8 frequencies, which may be more than num_nodes—having these stored helps the system be tolerant to adding and removing hardware. That said, you could simply examine the leaderboard data. The timer does not show disabled pilots or channels in this data.

2: Right now if you ask for something out of bounds it'll likely return null. Is the total number of entries a useful bit of information to spend time calculating and return? What would you do with that information that the /all endpoints don't already have covered?

3: I don't think the winner is exposed at all right now; that's probably a good one to include. As far as the last valid heat, I'd say that's related to #5  which needs a similar solution.

**Comment by HazardCreative** [comment]
A read implementation is now merged in. There's no write capability, but better auth is needed before that's really viable.
