### ISSUE TITLE
Feature request: Add preset buttons

### ISSUE THREAD

**Issue by BoLtWD** [RotorHazard/RotorHazard#57]
Add a preset button for IMD rating: 67 better than IMD 6C of 29

Also is it possible to add custom presets where someone can save a set of there own

**Comment by HazardCreative** [comment]
I don't understand what you're asking for a preset of IMD 67? The IMD rating is calculated based on the current frequency set. Can you elaborate? What set do you suggest?

You can use profiles to construct your own frequency sets, which is arguably better because you will save your node tuning values along with them and you can easily switch sets, (by changing profiles,) on the race page. Why would another preset button be preferred?

**Comment by BoLtWD** [comment]
Sorry I forgot to add information to my post. 
Using imdtabler I have found ETBest6 : 5645 5685 5760 5805 5905 5945, gives a IMD= 67 while  IMD 6C gives a  IMD=  29.  

If 100=best then ETBest6  is better than IMD 6C.   

My request is to add preset button for  ETBest6

**Comment by HazardCreative** [comment]
5645 and 5945 are outside the FCC allocation for the 5.8GHz spectrum in the United States, so they are illegal to use even for pilots that hold an amateur radio license. That's the primary reason for leaving them out of the presets; I don't want to encourage their use.

**Comment by BoLtWD** [comment]
valid point
