### ISSUE TITLE
Auto adjust ExitAT and EnterAt

### ISSUE THREAD

**Issue by BoLtWD** [RotorHazard/RotorHazard#63]
I was wondering why when you press Capture for ExitAT is sets some of the nodes lower than PassNadir. You sometimes have to do the same and adjust manually EnterAt as its now close to ExitAT.

If ExitAT should not be lower than PassNadir and EnterAt should not be close to ExitAT then why can’t the code auto adjust for this or at least have a button to Auto adjust ExitAT and EnterAt so they are within the correct limits?

If above is not possible then why would I Capture ExitAT lower than PassNadir especially when passes wont register ?

**Comment by HazardCreative** [comment]
* The PassNadir value can't be relied on for setting Enter and Exit. The data might be invalid because nobody has flown the course yet or the node might have changed frequencies. A warning is worthwhile to let you know you're doing something potentially problematic, but automatically adjusting the values could give you something that doesn't work at all if the timer assumed something that wasn't true based on invalid data.
* Pressing the button tells the timer "the currently read RSSI is correct". This is a manual adjustment and the timer will accept the command you give it without question.
* The catch/force end buttons do auto-adjustment in some cases, because that's what they are designed for. With these buttons there is still plenty of room for error if the assumptions are wrong, such as pushing them when no recent pass has occurred.
* You might decide to capture ExitAt lower than PassNadir if someone was recently just flying around and ignoring the course. That could record a high Nadir if the gate is triggered twice without flying very far away in between.

This is why the warnings are issued, but ultimately it's up to the user to understand what's happening on the course and if the warnings can be ignored.

If you are paying attention during practice time, you can quickly dial in values using only the 'catch lap' and 'force end' buttons to auto-adjust the values. It's pretty efficient but requires pilots to be actively flying the course so you can't do it alone.

I expect at some point I will add in an 'auto-calibration' option not dissimilar to the Delta5, but the timer's accuracy will always be lower this way vs. getting a good manual tune up front.

**Comment by BoLtWD** [comment]
Thank you
