### ISSUE TITLE
Use Split Timers to control 3rd party software (f.e. switch between Event Cameras/Scenes in OBS)

### ISSUE THREAD

**Issue by HiTilt-FPV** [RotorHazard/RotorHazard#635]
I propose giving RH the ability to interact with 3rd party Programs running on the Managing-PC.

Example 1:
I use OBS to stream Races on twitch, and i have have a part of the screen that shows camera scenes viewing parts of the course (complex obstacles or the start/finish gate, for example).  Using Split timers close to these obstacles, RH triggers OBS to switch between those scenes, making them follow the first pilot (or 3rd pilot, or *pilotname*) around the course.

Example 2:
I have a highspeed Camera setup in line with the start/finish gate. I want to use this camera to detect if two pilots crossed the finish gate at the same time, who was first and won the race. So i set up a Split timer 5m before the finish gate and the master timer at the finish gate. The camera starts filming when the first split timer gets triggered the first time and stop shortly after the master timer gets triggered the first time.

Example 3:
RH knows which pilot won and when he won, and triggers a soundtool to play a little jingle the pilot likes to be played. I could also trigger a little lightshow going off on the track and much more...

My Ideas for Implementation:
a) RH can trigger the browser to say pilot names and lap-times. Maybe there is a similar way to trigger hotkeys (like Alt+shift+1 for camera 1 in OBS).
b) Use a USB-Node to emulate keyboard inputs.
c) (the most powerful, i believe) have a little Program installed to the Managing PC that is capable of emulating hotkeys or interact with 3rd party programs via plugins or else)

**Additional features:
A Mute/Unmute button, to stop RH from controlling the 3rd party programs if it is not desired.

**Comment by pulquero** [comment]
I have a development branch where I've been trying out some ideas in this area. It might be worth you evaluating it so we have a more informed idea of what type of things might work and what won't.

**Comment by HiTilt-FPV** [comment]
I believe this is a hint to the mqtt server you implemented on your dev branch? I looked it up and found the following events emitting a message (tell me if i missed some):
            self.addEvent(Evt.RACE_START, race_start)
            self.addEvent(Evt.RACE_LAP_RECORDED, race_lap)
            self.addEvent(Evt.RACE_FINISH, race_finish)
            self.addEvent(Evt.RACE_STOP, race_stop)

I don't know what Lap recorded does, but i think Race -start, -stop and -finish are good starts. But for, lets say, an OBS Studio Plugin, the split timing abilities of RH are even more interesting. Informations like
- Pilot Name/Tag and Position (1st place, 2nd place...) after each start/finish gate crossing
- Pilot Name/Tag and Position (1st place, 2nd place...) after each split timer
(Position changes between two split timers and throughout the course)
- Time difference between pilots and changes throughout the course

would be very interesting for use in OBS. FPV is hard to watch, for media(video) -crew and spectators alike. The placement informations mentioned above can help automate the process of following the drones around the track with a camera. This should make for a much better viewing experience.

**Comment by pulquero** [comment]
RACE_LAP_RECORDED are the actual lap passes. Split timing comes for free in that timer IDs are included in the mqtt topics, and multiple timers are free to publish to the same broker, so a single subscriber will precisely be able to track pilots round the track. In fact, I'm working with @Aaronsss to enable the type of things you mention with his cheap per-gate timing hardware. 

I think there's also scope to move beyond the current one RH server per gate model. I'm experimenting with the idea of being able to explicitly assign individual nodes to gates and pilots. This should enable more deployment options to make split timing more accessible.

**Comment by JesseFPV** [comment]
Just a thought:
Isn’t it more logical to create a OBS plugin that listens to the sockets that the RH system is broadcasting on the local network?

**Comment by pulquero** [comment]
Sure, using the sockets system would be one way to do it. You would need to do some work to make it fit for purpose. Then it turns into a question of how best to spend the effort - patching the old stuff or designing something fit for purpose from scratch. Since there are several use-cases I want to implement, it made more sense to purpose-build something.

I've now got as far as being able to track a quad round a track on a map as it passes various split timers. This could probably be turned into an OBS overlay. If anyone wants to try that or a plugin I'm happy to provide assistance.

**Comment by JesseFPV** [comment]
Would love to see how it works!

**Comment by HiTilt-FPV** [comment]
> Just a thought: Isn’t it more logical to create a OBS plugin that listens to the sockets that the RH system is broadcasting on the local network?

Well yes, it may be. But if MQTT is already in the works for RH it is more convenient to use that. MQTT has the advantage that implementing it into other software is relatively simple and often already done. OBS for example already has several plugins that implement MQTT Brokers to talk to other devices, like an ESP32 controlled LED Display.

**Comment by JesseFPV** [comment]
> > Just a thought: Isn’t it more logical to create a OBS plugin that listens to the sockets that the RH system is broadcasting on the local network?
> 
> Well yes, it may be. But if MQTT is already in the works for RH it is more convenient to use that. MQTT has the advantage that implementing it into other software is relatively simple and often already done. OBS for example already has several plugins that implement MQTT Brokers to talk to other devices, like an ESP32 controlled LED Display.

100% agree but I am afraid for may purposes the delay is too high? You really need a few ms to trigger the camera to change otherwise it's already passed by... Maybe its quick enough I have not used MQTT recently.

**Comment by pulquero** [comment]
With a local broker, MQTT is quite fast. It also has less overhead than websockets (depending on choice of communication protocol). You could even use an embedded (same process) broker to really minimize delays. But, getting a bit sidetracked here. Let's not forget what we are talking about: N split timers that need to communicate with a single endpoint, eg OBS. With websockets, you would have to either attach your endpoint to each individual timer, maintaining N connections, or make a single connection to the primary timer, and have the split timers forward to the primary timer. With MQTT, the endpoint and each timer just make a single connection to the broker. And you can choose where to place the broker. Now, add a bunch of connections for people browsing result web pages, and appropriate security. Which do you prefer? Consider this, the connection to a split timer goes down. With MQTT, the OBS plugin will just gracefully stop receiving messages. It doesn't need a whole bunch of error handling code. There isn't going to be an avalanche of incoming connections when the split timer reestablishes contact.

As for the camera use-case, I have low-level mqtt events for pass-start/pass-end, so you could trigger the camera as the quad *approaches* the gate. If you have capable hardware (e.g. esp32), these events can also be sent directly from the node itself. This should help ensure the camera is triggered in time. My general advice would be to try to design around the latency rather than focus on absolutely minimising it. I mean you need to have a reasonably small latency, but things like camera placement and course design will probably yield the biggest benefits, else you are just in an arms race between electronic speed and quad speed (i.e. ideally you want to minimise variability in the quality of the output by not being too dependent on the delay.)

Let me finish by saying that maybe MQTT isn't 'the answer', but I believe it is closer to the answer than websockets. And in an agile world, we are doing well if we are taking a step forward.

**Comment by HazardCreative** [comment]
Plugins now allow code to be loaded into the timer which can react to timer events. for example, here's how one can be deployed to send UDP messages as Action Events. https://github.com/JesseFPV/RH-Plugin-EventAction-UDP-Message
