### ISSUE TITLE
JSON api endpoint containing time remaining in ongoing heat

### ISSUE THREAD

**Issue by fireduckfpv** [RotorHazard/RotorHazard#639]
I am working on implementing a 3rd party video / time visualizer using JSON data and I have found almost all the values I need in the JSON endpoints. Good job guys! :) 
But I can not figure out how to show how much time there is left in the ongoing heat. Have I missed something? Is there an endpoint that has it?

I am considering using the api/Status.race_status to start a timer when it is "1" and stop it when it is "2", but then I need to know total heat time. Is there a JSON value for that?

**Comment by pulquero** [comment]
Essentially, you are looking to do something like a progress bar for elapsed race time? I think the best option is to get the race format info, get the length of the race and then just count down that from the start time. Is it going to be super precise? no, but do you need it to be? You could poll for the race status every so often too, to check the race is still running (assuming there is an endpoint to do that).

**Comment by tomidland** [comment]
Thank you, I see now that "api/format/all" contains "race_time_sec" on all formats if they have been set to a time. I do not need it to be precise, so this could work. But it would be nice with a pre-formatted time remaining on current heat though. :)

**Comment by tomidland** [comment]
Hum, I find all the race types with names and id in "api/format/all" but I can not seem to find a way to identify what id of race is currently running.

**Comment by pulquero** [comment]
You might need to listen to the  websockets to get current running info. The api is really just a dump of internal database objects. So if the information hasnt been persisted then it is probably not available via those endpoints.

**Comment by tomidland** [comment]
Oki, thank you. :) Is there a wiki on how to use websockets in Rotorhazard?

**Comment by pulquero** [comment]
No, I would just start by opening browser dev tools on the 'Run' page and take a look at the web socket activity.

**Comment by tomidland** [comment]
Will do :)

**Comment by martinglass** [comment]
> Essentially, you are looking to do something like a progress bar for elapsed race time? I think the best option is to get the race format info, get the length of the race and then just count down that from the start time. Is it going to be super precise? no, but do you need it to be? You could poll for the race status every so often too, to check the race is still running (assuming there is an endpoint to do that).

Livetime goes a step further and uses the "pace" to calculate the estimated laps/finish time and then present it as live data in the race view. Observers can see how well each pilot is doing relative to the others.

**Comment by HazardCreative** [comment]
I limited the realtime outputs in the JSON endpoints somewhat because it's my experience that participants have a high expectation of accuracy, and this API can't provide it. Networks/systems often have lag—sometimes very significant on WiFi—so continuous polling of a 'time remaining' value would not make for a smooth display at all. It's best, as said above, to have the display subtract the current time from the start time + total race time.

One method is to ensure your timer and other devices on the network have synchronized internal clocks, usually with something like NTP. Then you can simply transmit timestamps and trust they are accurate regardless of when they arrive. RH's split timing over a network uses this method.

Another method is to determine the clock offset between your device and the timer. It's more challenging because you have to take multiple samples and filter them to arrive at a best guess, but sometimes NTP or the like isn't available. This is the method RH uses for the browser because their clocks can't be trusted and there are no adjustment controls available. We have the socket endpoints needed to do this; see https://github.com/RotorHazard/RotorHazard/blob/main/src/server/templates/run.html#L47-L103

It's been some time since I worked with that API. Not outputting the current race format and/or start time sounds like an oversight that should be corrected.

**Comment by tomidland** [comment]
Thanks for the insight! :) 
Time remaining is not very important on an information screen in regular qualifier heats, but in a teamrace with most laps in 30 minutes it is nice to have. But as mentioned, it does not need to be very accurate. It would be nice to know what kind of race is currently going on though, so I can fetch the correct race_time :)

**Comment by HazardCreative** [comment]
RH4 now supports plugins and a dedicated API. The JSON endpoints aren't likely to get much additional functionality as RHAPI offers better access, performance, and data security. See https://github.com/RotorHazard/RotorHazard/blob/main/doc/Plugins.md .
