### ISSUE TITLE
Error initializing LED support

### ISSUE THREAD

**Issue by dieselshroom** [RotorHazard/RotorHazard#645]
Making a single node personal timer with a RPI Zero 2. Everything is going fine until trying to add an LED. Wanting to run an Adafruit NeoPixel Stick with it. I enabled LEDs in the config.json and rebooted the server. LED support fails with:
RuntimeError('ws2811_init failed with code {0} ({1})'.format(resp, str_resp))
RuntimeError: ws2811_init failed with code -3 (Hardware revision is not supported)

I am including the log. Any thoughts?

[rh_20220111_192249.log](https://github.com/RotorHazard/RotorHazard/files/7850978/rh_20220111_192249.log)

**Comment by HazardCreative** [comment]
The LED library will need an update since only 4.3 supports the Pi Zero 2. RH 3.1 has been tested with v4.2 so that's what gets installed when you run the included script. Try upgrading the LED library yourself. Run `pip3 install --upgrade rpi-ws281x` and make sure you get 4.3.1 (or later). RH is untested with this version, but it'll probably be fine.
