### ISSUE TITLE
Current heat stream displays loading... and does not load

### ISSUE THREAD

**Issue by Aaronsss** [RotorHazard/RotorHazard#706]
I was trying to use Current Heat (/stream/heat/0) for OBS and noticed that it displays loading... very often and does not update until a page reload and somtimes not even then. It was doing this directly when viewed in the web browser too.

I was using RH 3.2.0

**Comment by HazardCreative** [comment]
I attempted to look at this locally and could not reproduce the issue. Do you have steps which can accomplish this?

**Comment by Aaronsss** [comment]
I go to /stream/heat/0 and I get this: 

![image](https://user-images.githubusercontent.com/23297034/224557963-ece0456a-9fc1-4e14-94f3-1004f1a649f6.png)

I get the above 95% of the time. 

Should it work through all phases of a race? 

I do get it at all phases of the race but sometime after 15-20 seconds it will load ok. Refreshing the page manually doesnt seem to make much diffrence

**Comment by HazardCreative** [comment]
Thanks for the update, the additional information is helpful, especially since I have yet to reproduce the issue on my own. Yes, the page should update normally though all phases of a race.

This sounds like a failure of the websocket connection, which recovers when its internal timeout comes back around. We're already looking at updating the socket library in this version, which will hopefully bring stability updates along with it. I think that's the first step in this issue as well. I'll try to update this issue and hopefully you can test again at that point.

**Comment by HazardCreative** [comment]
Please update to 4.0.0-dev.7 and re-test.

**Comment by HazardCreative** [comment]
Closing after no response; please update to the latest version and re-raise if the issue occurs again.
