### ISSUE TITLE
Ranking from abitrary percentage

### ISSUE THREAD

**Issue by Aaronsss** [RotorHazard/RotorHazard#718]
Is it possible to have finals seeded based on some arbitrary percentage instead of 1 to 5 rounds?

In UK pilot packs are typically specified as best 60% or some other percentage of completed rounds count towards the ranking. Doing it with a percentage allows us to run as many rounds as time will permit without having to go back and modify the event setup if it start raining for example. 

Currently the ranking option gets greyed out once the first race is run

**Comment by martinglass** [comment]
I know it’s technically the same as a percentage (x/N *100%), but more formally in the UK, the final rankings are determined from the best x rounds out of N total rounds, where x is at least half of N and x is decided by the race director at some point during the proceedings. 
For example, if 10 qualifying rounds were expected with only the best 5 being counted, but time allowed for an extra round, making 11 in all, the final ranking would be chosen among the best 6 out of 11 rounds.
Another example, if 10 qualifying rounds were expected with only the best 5 being counted, but rain curtailed the event after 7 rounds, the final placings would be calculated from the best among between 4 and 7 rounds, chosen at the race director’s discretion.
I hope that sheds a bit more light. 
Correct me if I’m wrong.

**Comment by Aaronsss** [comment]
I have seen it done both ways. Personally I prefer percentage and stating if you round up or down as its easier to understand at the start of the race rather than let the RD pick an arbitrary number of rounds towards the end of the race. Which leaves you guessing as to your progress until finals are seeded.

**Comment by HazardCreative** [comment]
Thanks for the issue. I will keep this in mind.

The 5-round limit is expected to be for the beta only, because creating a UI for ranking parameters would have delayed the beta release.

Changing the format or ranking condition during an event is generally considered bad practice, as the pilots don't know what to expect. It's a bit like changing the rules of a game while you're playing it. However, RH does not stop you from doing so; the RD can override this by simply unlocking the class.

I'd argue that "best % rounds" leaves pilots guessing more than "best X rounds". With "best X", all of your rounds count until you hit the minimum and after that you can only improve. A % will remove rounds that may end up being added in later—if you don't improve in later heats, your average could go down. That's not to say I won't implement it, just something to think about.

**Comment by martinglass** [comment]
It happens in UK BQEs - for example, where weather interferes with the proceedings and pilots are left guessing about how many rounds will count in the end.
I’ve seen times when the expected number of qualifying rounds wasn’t met. I’ve been to BQEs where the whole triple final section was cancelled due to rain. 
I’ve also seen times when the RD was able to add one more qualifying round (for example, from 10 to 11) before the Finals and he upped the count by one (from 5 to 6). Not best practice, maybe, but the RD’s job is to maximise the opportunities for all, and with weather as unpredictable as it is in the UK, pilots have to be prepared for these things.

**Comment by HazardCreative** [comment]
Bundling a %-based number of rounds isn't planned at this time, but this feature can now be added via a plugin. The existing "Best X rounds" bundled plugin would be a good start.

It's possible that I may develop this myself, but it would be made available somewhere outside the RH core.

**Comment by HazardCreative** [comment]
https://github.com/HazardCreative/RotorHazard-Class-Rank-Best-Percentage
