### ISSUE TITLE
Support 'Discard New Short Laps' in marshaling

### ISSUE THREAD

**Issue by Awakeli** [RotorHazard/RotorHazard#840]
**Describe the bug**
After using the Marshal page to set threshold levels, 'Minimum Lap Behaviour' reverts to 'Highlight New Short Laps' even though 'Discard New Short Laps' has been set.

**To Reproduce**
1. Set Min Lap Behaviour to Discard.
2. Run race ensuring some laps are under minimum lap time. Save lap times.
3. Go to Marshal page.
4. Adjust threshold levels, click Recalculate Race.
5. At this point laps under the minimum lap time are highlighted and not automatically deleted.

**Expected behavior**
With minimum lap behaviour set to 'discard new short laps'
[New folder (2).zip](https://github.com/RotorHazard/RotorHazard/files/13878158/New.folder.2.zip)
, laps under the minimum lap time should be automatically deleted after adjusting thresholds in marshal page.

**Screenshots**
Attached.

**Log Dump**
Attached.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser chrome
 - Version 120.0.6099.200

**Comment by HazardCreative** [comment]
This is intentional behavior. Automatic deletion is a poor method to determine which pass is valid. Consider the case when a pilot comes close to but misses the start gate. The pilot then circles around to begin the new lap. In this case the correct crossing which should be marked is the second of the two. It would be incorrectly discarded with the automatic behavior.

If you are getting too many false reads, try [improving your RF shielding, adjusting your timer location](https://github.com/RotorHazard/RotorHazard/blob/main/doc/Shielding%20and%20Course%20Position.md), or adjusting your course lines further away from the timing gate.

**Comment by Awakeli** [comment]
Automatically deleting short laps works well enough for our small tiny whoop group, in which I don't have time to fly and do a large amount of marshalling.

With the Minimum Lap Behaviour set to 'Discard New Short Laps' automatic deletion works fine. The problem comes after adjusting lap detection thresholds in the Marshal page, when the Minimum Lap Behaviour changes it's self to 'Highlight New Short Laps'

**Comment by HazardCreative** [comment]
The min lap behavior applies to realtime races, not marshaling. If you go back to running a race, the setting is still set to discard, yes? If not, that would be a bug. 

As a feature request for marshaling, though, I will give this some thought. Perhaps there is a way to automate this while ensuring accuracy is easy to achieve.
