### ISSUE TITLE
Race start cancelled in FPV Trackside when using Rotorhazard

### ISSUE THREAD

**Issue by MacDaddyFPV** [RotorHazard/RotorHazard#892]
Connection lost to timer and race cancelled in FPV Trackside

In FPV Trackside with a Rotorhazard timer connected, Start a race and wait to see if the race start is cancelled.

Expected the race to start and start buzzer to sound

Logs
[Trackside Log.txt](https://github.com/RotorHazard/RotorHazard/files/15024665/Trackside.Log.txt)
[Rotorhazard log.txt](https://github.com/RotorHazard/RotorHazard/files/15024668/Rotorhazard.log.txt)

 - OS: Windows 11
 - Browser NA
 - Version Main, Beta and many previous versions

**Comment by HazardCreative** [comment]
There isn't really enough data here to track down any specific issue, but I'm interested if the issue persists after the recent performance upgrades. These should improve both the sites and reliability of the connection, which could have affected this.

If the issue is not fixed, please get a full log dump with database, and provide a log from trackside that was captured at the same time.

**Comment by HazardCreative** [comment]
Closing after inactivity. Reopen if the issue resurfaces.
